-- AlterTable
ALTER TABLE "User" ADD COLUMN     "averageRevisionJuz" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN     "averageSabaqPages" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "averageSabaqParaPages" DOUBLE PRECISION NOT NULL DEFAULT 3;
